### PR TITLE
Very close to feature complete fork

### PR DESCRIPTION
**Pull request by rohan-deshpande**
Hey there! Awesome package man. I needed this for something I'm building and this served as an excellent starting point. 

I started out with the aim to port as much of the original implementation as I could while following your patterns / ideas, here's a demo: https://rohan-deshpande.github.io/react-dat-gui/

As a result I've made a bunch of changes, here is my change log:

# Release Notes

### Changed

* ES7 property initializers are now used to set initial state in all components rather than `componentWillMount`

### Added

* A lot of documentation to the README
* Deploy script to `./example` app which deploys to github pages

### Changed

* Changed default export from `Dat` to `DatGui`

### Changed

* Removed custom check box styling from `DatBoolean` component
* Ensured sliders are the same height as number inputs
* Minor style changes for consistency

### Changed  

* Housekeeping in preparation for `v1.0.0`

### Added

* `DatPresets` component - this allows you to set presets for your DatGUI component and switch between them easily

### Changed

* Removed final reference to `reactcss`, this can be completely removed from dependencies now
* Removed unnecessary arrow functions in some `setState` callbacks
* Fixed bug where `DatNumber` input updates weren't updating sliders

### Added  

* `DatColor` component - this allows color pickers, powered by `react-color` to be rendered for mutating colors
* Added `example:promote` script for pushing development code up from `example/src/dev` into `src`

### Changed

* Example updated with `DatColor` included

### Added

* `DatSelect` component

### Changed

* Example updated with `DatSelect` included

### Added

* Support for nested folders via `DatFolder`

### Changed  

* Example `App.js` has been updated to include a nested folder example

### Changed

* SCSS is now broken up into partials which align with the various components

### Added

* Added `DatFolder` component
* Added this to the example

### Changed

* Updated component files to use `.js` file extension rather than `.jsx`
* Removed `examples` directory and created single `example` directory which is now powered by `create-react-app`
* Rewrote `webpack.config.js` so that it is compatible with Webpack v2
* Updated a bunch of dependencies in `package.json`
* Separated out `Slider` component from `DatNumber` and also added `utils` file
* Switched all event handlers in components to ES7 syntax
* Some code formatting
* Changed `build` directory to `dist`

### Added

* `example` directory
* `src/components/Slider.js`
* `src/components/utils.js`
* `src/style` directory
* `.editorconfig` file
* `.eslintrc.json` file
* `.babelrc` file
* `scripts` directory
* A number of `npm` scripts to `package.json`
* This change log!

### Removed

* The build no longer creates minified files, can add these back if required but I think it's better for the user to perform this step in their own build pipeline
* ES5 examples, don't think many people are coding with React and ES5 nowadays

The repo has changed a bit as a result. I'm using `create-react-app` for the `dev` and `example` apps now. The demo is something I whipped up quick because I couldn't find the source code to yours, it's now easily pushed to GItHub pages via an npm script. Would be happy to update back to what you had if you can make the source available. I'm thinking about doing one with threejs though.

Let me know what you think of this, quite keen to get it merged back as there's a couple more features I'd like to add including local storage saving/loading and time travel.

### CODE REVIEW

**Comment by claus** [comment]
omg <3

**Comment by claus** [comment]
@rohan-deshpande thank you so so much, you are a hero!

**Comment by rohan-deshpande** [comment]
Whoa thanks for the fast merge, I better update the readme!

Here's a pic of it in action inside my game engine

screen shot 2017-10-11 at 12 42 19 pm

**Comment by claus** [comment]
I already updated the readme, see above. Also, `1.0.2` is live on npm 🎉

**Pull request merged**
