### PR TITLE
Upgrade Webpack to Rollup, replace deprecated componentWillReceiveProps, linting fixes

### PR DESCRIPTION
**Pull request by tim-soft**
This wound up being a fairly large PR :man_shrugging:

I've replaced the Webpack v2 setup with the latest [Rollup Bundler](https://github.com/rollup/rollup) for the build process, which has drastically shrank the bundle size and also made the library much easier to work on locally. The build step also now outputs `es` and `cjs` bundles.

Here's how the new build compares to what is in the repo now :boom:
react-dat-gui.js `420kb  -> 32kb`
react-dat-gui.js.map  `509kb  -> 43kb`

React is deprecating the `componentWillReceiveProps` lifecycle method and will stop working in v17, I went ahead and reimplemented the logic with `getDerivedStateFromProps`. I also fixed a lot of linting/accessibility issues with the individual components.

All of the tooling has been upgraded i.e. babel/eslint as well as adding in prettier
The `/example` site is now next.js and much lighter-weight/faster -- new local dev instructions are in the readme

I'm marking this as a draft for now to double check all of the default props, a lot of them were missing and I'm not sure what is actually required in every case

[Here's a Codesandbox demo](https://codesandbox.io/s/react-dat-gui-rp62o?fontsize=14&module=%2Fsrc%2Fcomponents%2FReactDatGui.js)

Bug fixes:
   - Default preset is stored separately so that it can be reapplied after changing to other presets
   - All built-in react-dat-gui components now accept className and style props
   - All built-in react-dat-gui components can now have a `labelWidth` prop which can override the `<DatGUI labelWidth>` container prop and in any valid CSS units
   - Automatically include styles, no longer require importing external stylesheet
   - Add linting and precommit scripts that run `prettier`, `eslint` and `stylelint` over the codebase
   - Implement folder collapse/expand animations

Cheers! @claus @rohan-deshpande

### CODE REVIEW

**Comment by rohan-deshpande** [comment]
Wow this is huge @tim-soft! 👊 respect!

How do you feel about adding `enzyme` or `react-test-utils` to this repo? I think it's probably really valuable at this point to have unit tests for everything. I'll pull this branch and check things out locally and maybe branch off it to add them if I have some time.

**Comment by tim-soft** [comment]
@rohan-deshpande I added in [testing-library](https://github.com/testing-library/react-testing-library) + Jest which seems to be the new hotness with a super basic test + coverage

One thing that is a little vague to me is the use of `liveUpdate` and `onUpdate()` in some of the dat components. `liveUpdate = true` means we use the `_onUpdateValue` and `liveUpdate = false` means use `onUpdate()` instead?

**Comment by rohan-deshpande** [comment]
Great stuff man. Just regarding 

> Default preset is stored separately so that it can be reapplied after changing to other presets

I've noticed in the codesandbox that switching between presets doesn't always work. Once you've made changes, switching to another preset doesn't seem to update state.

**Comment by tim-soft** [comment]
`<DatPreset />`'s current intended behavior(?) works like this

1. You pass in an array of presets
2. The initial state of DatGUI is called the "Default" preset

The demo code is straight from the master branch, maybe this is where the preset switching doesn't work for you
```
// Presets update on every state change...
const presets = [
  { A: { ...data, ...presetA } },
  { B: { ...data, string: 'Preset B' } },
  { C: { ...data, string: 'Preset C' } }
];
```

So every time you switch to Preset A/B/C they wind up overwriting each other, but you can always switch back to the "Default" preset

**Comment by tim-soft** [comment]
Stress testing this PR on my particle library [react-particles-webgl](github.com/tim-soft/react-particles-webgl) in production here: https://timellenberger.com/particles

Everything seems to be working, there are a few other things to do like upgrading gh-pages and unit testing although these things could go in a different PR, I'll go ahead and mark as ready to review

**Comment by rohan-deshpande** [comment]
I've tried pulling the branch and running `npm install`, I'm getting a tonne of errors related to node-sass though. Noticed that you seem to have switched to yarn, personally I'd prefer to keep things standardised with npm for this but I don't see a reason as to why I'd be getting these errors... potentially an issue with `"rollup-plugin-scss": "^1.0.2",`?

**Comment by rohan-deshpande** [comment]
> `<DatPreset />`'s current intended behavior(?) works like this
> 
> 1. You pass in an array of presets
> 2. The initial state of DatGUI is called the "Default" preset
> 
> The demo code is straight from the master branch, maybe this is where the preset switching doesn't work for you
> 
> ```
> // Presets update on every state change...
> const presets = [
>   { A: { ...data, ...presetA } },
>   { B: { ...data, string: 'Preset B' } },
>   { C: { ...data, string: 'Preset C' } }
> ];
> ```
> 
> So every time you switch to Preset A/B/C they wind up overwriting each other, but you can always switch back to the "Default" preset
> 
> Here's a [Codesandbox](https://codesandbox.io/s/react-dat-gui-emjcf?fontsize=14&module=%2Fsrc%2Fcomponents%2FReactDatGui.js) where presets A/B/C only extend the _initial_ state instead of the current one
> 
> edit: what is the benefit of having the current preset structure versus this?
> 
> ```
> const presets = [
>   {  _name: 'Preset A' },
>   {  _name: 'Preset B' },
>   {  _name: 'Preset C' }
> ];
> ```

Hey so just on this, I'm still seeing a functionality mismatch. To reproduce:

* Go here https://claus.github.io/react-dat-gui/
* Change your preset to `A`
* Mutate some properties
* Now change your preset to `B`
* You'll notice that the preset updates to `B`'s properties

Do the same in your codesandbox and after selecting the `A` preset, subsequently choosing the `B` preset doesn't do anything.

**Comment by tim-soft** [comment]
You _may_ be looking at an older version of the sandbox, I can't repro. If you look at the preset code in the sandbox, Presets A and B are complete state overwrites. Preset C takes the default preset and changes the string value, Preset D will modify whatever the last preset was..

I haven't used npm in a long time, but I can tell you that all dependencies are up to date and I'm using Node 12.8.0 on Windows 10 with visual c++ binaries

**Comment by rohan-deshpande** [comment]
Okay, so `yarn install` worked. I'm a little uncomfortable with this, don't know why it would happen, both should be supported with a preference towards npm honestly. Can you try `npm install` to see if it works?

Will checkout the rest of the functionality now.

**Comment by tim-soft** [comment]
I just ran through the install with NPM and didn't get any errors. I'm pretty sure node-sass involves building some binaries, you may need to clear your cache and/or install any missing node-sass build dependencies for your environment.

The only issue I see with using npm is finding a replacement for `yarn link`

**Comment by rohan-deshpande** [comment]
> I just ran through the install with NPM and didn't get any errors. I'm pretty sure node-sass involves building some binaries, you may need to clear your cache and/or install any missing node-sass build dependencies for your environment.
> 
> The only issue I see with using npm is finding a replacement for `yarn link`

Yah I had my Sunday hat on and was being dumb, was still on master and not on your branch. NPM install issues are fine. 

Yeah the `yarn link` thing is pretty cool, completely removes the need for scripts to move stuff back and forth between the example and the root while tinkering. I like it. Would be great if there was an `npm` solution... I'll do some digging

**Comment by tim-soft** [comment]
I can do that now that we run `prettier` + `eslint` + `stylelint` over your code in a pre-commit hook

**Comment by tim-soft** [comment]
For doing _development_ specifically on this package, requiring yarn isn't much of a stretch imo.

@rohan-deshpande do you want to setup travis-ci to run tests + build on each commit? I can add in a config for it

**Comment by rohan-deshpande** [comment]
> For doing _development_ specifically on this package, requiring yarn isn't much of a stretch imo.
> 
> @rohan-deshpande do you want to setup travis-ci to run tests + build on each commit? I can add in a config for it

Yah it's cool, just need to document it in the README I guess just so that people who wanna do PRs don't get confused when `npm install` doesn't work inside `./example` 

Re: travis, yes this would be an awesome addition especially since we have a testing framework now.

**Comment by rohan-deshpande** [comment]
@tim-soft I think it might be better if the animation stuff is in a separate PR... this one is already very huge. I know I put the animations in the TODO list, but I do wonder if they are necessary, given that you are now using another lib to do them and this will impact bundle size. The question is, do we really need them?

**Comment by rohan-deshpande** [comment]
> Good question. For reference you can see what the new animations look like here: https://timellenberger.com/particles -- I think they add some polish to the library and bring it closer to parity with dat.GUI. The bundle implications seem pretty insignificant, all things considered.
> 
> Aside from the animations does the PR look good to go?

It looks really good but I need to spend a bit more time with it as it is quite large, but basically looks fine. I might have a bit of time this weekend.

**Comment by rohan-deshpande** [comment]
@tim-soft reviewing more now, just FYI, I found the `npm` equivalent to yarn's `link`; it's `file:`

**Comment by rohan-deshpande** [comment]
@claus I think this is good to go, I'm gonna merge it! Massive respect once again @tim-soft, just note, I may have a PR up to change things back to `npm` soon, would prefer to stick with it over yarn but it can be done in separate PR and I don't want to hold this one up any longer.

**Comment by tim-soft** [comment]
@rohan-deshpande Cheers! You can also `yarn deploy` in the root dir which will build the example next site and push it to gh-pages, overwriting the old one

**Comment by rohan-deshpande** [comment]
Thanks, hmm I am getting an error when running `yarn deploy`

```
$ shx rm -rf out
/bin/sh: shx: command not found
```

**Comment by tim-soft** [comment]
Make sure you run `yarn install` in /example, shx is a dev dep

**Comment by rohan-deshpande** [comment]
Oh so this is a package that allows for cross platform linux like commands via node?

**Comment by rohan-deshpande** [comment]
Deployed 🎉 https://claus.github.io/react-dat-gui/

**Comment by claus** [comment]
Screen Shot 2019-09-02 at 14 39 13

🎉

**Pull request merged**
