### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by rohan-deshpande**
# Release Notes

### Added

* Section on React version to README
* Point regarding animations for `DatFolder` to Roadmap
* License section to README

### CODE REVIEW

**Comment by rohan-deshpande** [comment]
I added a section about the react version to the README because I tried to pull the package into my app which was using `^15.0.0` and I got errors. Pretty sure they were due to conflicts. Updating to `v16.0.0` fixed these.

**Comment by claus** [comment]
I think we should investigate further why this breaks in pre-fiber React. Sounds more like a bug than a hard peer dependency requirement to me. I'll see if i can replicate the issue..

**Comment by rohan-deshpande** [comment]
Import the package in an app that uses v15 and you'll see the issue. 

It's been reported elsewhere as well. 

It makes sense to me - if you upgrade your app to v16 and you are using v15 components, you'll be fine. This is because v16 is backwards compatible. 

But it's not forwards compatible. If an app is v15 and tries to use v16 components, it will throw errors.

**Comment by rohan-deshpande** [comment]
I mean v15 isn't forwards compatible. The underlying algorithms have changed drastically.

**Comment by claus** [comment]
> Import the package in an app that uses v15 and you'll see the issue.
> It's been reported elsewhere as well.

Which errors have been reported exactly? Because the errors that i'm seeing when plugging `react-dat-gui` into a v15 app are fixable, i think.

**Comment by rohan-deshpande** [comment]
Hmm really? I'll have a look again.

**Comment by claus** [comment]
I have `DatBoolean` working in both v15 and v16 apps, check out https://github.com/claus/react-dat-gui/tree/fix-react-dependency (work in progress)

**Comment by claus** [comment]
I think it boils down to:
* `setState` update callback is wonky, especially in form change handlers
* `findDOMNode` should (and can) be avoided
* in package.json, `react` and `react-dom` must be in `peerDependencies`, with a more permissive version tag

**Comment by rohan-deshpande** [comment]
Hey, did you get any further with this?

**Comment by rohan-deshpande** [comment]
I'd like to get this merged, I'll fix the conflicts and do a major version update to avoid breaking anyone's current installs if that's okay? I think we should move towards up to date react support anyway

**Comment by claus** [comment]
Yeah i think by now, we can expect a v16 peer

**Comment by rohan-deshpande** [comment]
> Yeah i think by now, we can expect a v16 peer

Wicked! I'll fix conflicts and merge. I've got floating point numbers working perfect in my other branch too so I'll submit a PR for that right after.

**Comment by claus** [comment]
Niiiice! 👍💯

**Pull request merged**
